---
# tasks file for ca_certificates
- name: install ca_certificates
  package:
    name: "{{ ca_certificates_packages }}"
    state: present
  register: ca_certificates_install_ca_certificates
  until: ca_certificates_install_ca_certificates is succeeded
  retries: 3
